name: auto-pr-on-new-version

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow when a tag with the version pattern is pushed

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name 'mjapi.io'
        git config --global user.email 'hi@mjapi.io'

    - name: Install npm deps
      run: npm install

    - name: Build ng
      run: npm run build

    - name: Check remote URL
      run: git remote -v
        
    - name: Create temp branch for the live pull request and push changes to it
      id: branch_creator
      run: |
        tag=${GITHUB_REF#refs/tags/}
        build_branch="build${tag}"
        git config lfs.https://github.com.locksverify false
        git subtree split --prefix=dist/mjapi --squash -b "$build_branch"
        git push origin "$build_branch" --set-upstream
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "build_branch=$build_branch" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        title: "Merge tag ${{ steps.branch_creator.outputs.tag }} into live"
        branch: ${{ steps.branch_creator.outputs.build_branch }}
        body: |
          This is an auto-generated pull request to merge the build from tag ${{ steps.branch_creator.outputs.tag }} into the live branch.
        base: 'live'  # Base branch to merge into
        token: ${{ secrets.GITHUB_TOKEN }}  # Token for the bot to authenticate
        labels: |
          automated pr
        delete-branch: true
